#!/bin/bash

# Declare an associative array
declare -A devices
devices=( ["V3_1"]="100.65.252.225" ["V3_2"]="100.65.253.43" ["V2_1"]="100.65.47.254" ["V2_2"]="100.64.197.31" )

# Loop over the devices
for device in "${!devices[@]}"; do
    ip=${devices[$device]}
    +clear-all-logs $ip
done

