#!/bin/bash

. plusScriptsPaths


if [ -z "$1" ]; then
  set -- "$1" "build"
  shift
fi

cd "$(git rev-parse --show-toplevel)" || exit 1

project_name=$(git remote get-url origin | awk -F '/' '{print $NF}' | sed 's/\.git$//')

recepie_file="$PS_DIR_BUILD_RES/$project_name"

echo "recepie_file: $recepie_file"

if [ -f "$PS_DIR_BUILD_RES/$project_name" ]; then
  echo "Build type: $project_name"
  source "$PS_DIR_BUILD_RES/$project_name" "$@"
else
  echo "No build script for $project_name"
  exit 1
fi