#!/bin/bash


if [ -z "$1" ] 
then
  echo "Please enter IP address"
  exit 
fi 

echo "IP is $1"

auth-wrapper ssh -v support@$1 "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && echo \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCv7YyYMakPHqAnk93e5usQYIYSry0y5hcn5EgFFa138JUDfUUo7cRCfRS2E6Gjw+8X6PcryZsvwuhkMb2J1ClnSBQs6Z1zxnJ0kobLl3acRSmbYag82zUY7n5N4tM8ii9a35QoGcM9LaICeFJvX/w4XPJPGQLl5KmqMrdsIHi6p/TjBiz2Kwh4QLpoKAL+RVHnwZEq39+ugE6VzUdAIhFlOgvVoAkrSKpYrBBVj1jh6d4J0dCTWoL0d6b7xgomwCWby1EmaUGtdgr2YNzhZ7dLlMOJkGE1bQ7lQUtF2Uxx3y7uhEROricVxmFsCVeoO3uNx/hJtqa5SlyKH/xgu7G3ua/lNWWdWovHPcVRwaS46AXzskCK6xxnxHaRX9lTLDuxsSgRt1MRSAE8Per9BCKOlCGI2dIv0xOHDAR1XkS4UyDEwU7BCdFKPUB8zh1CNu7qIAVutBFlwN1Ic7RXjBM7JVC9ZsZmg0QDtwXQw5ljdSkwH1oYprU2XZwqIOolIih5pXPWUaaodL/J4kl+1Wzy7TYpgaN5agWyg1Y9d/jpbnKdBYS0LfQk+7BTq7YkoQWvx3/PJ+ZU/kGcced8vgJQ/vj6xMtJj5Ji9R2kzYp9ct8u5/WHTGSsl6vN2lu6P4bdeJqsBWlJ0ZFv4FXzyUP0EWzN80RLiCtrqEjj/IKz3w== tm@connectedcars.dk\" >> ~/.ssh/authorized_keys"
# auth-wrapper ssh -v support@$1 "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys"
auth-wrapper ssh -v support@192.168.7.1 "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && echo \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCv7YyYMakPHqAnk93e5usQYIYSry0y5hcn5EgFFa138JUDfUUo7cRCfRS2E6Gjw+8X6PcryZsvwuhkMb2J1ClnSBQs6Z1zxnJ0kobLl3acRSmbYag82zUY7n5N4tM8ii9a35QoGcM9LaICeFJvX/w4XPJPGQLl5KmqMrdsIHi6p/TjBiz2Kwh4QLpoKAL+RVHnwZEq39+ugE6VzUdAIhFlOgvVoAkrSKpYrBBVj1jh6d4J0dCTWoL0d6b7xgomwCWby1EmaUGtdgr2YNzhZ7dLlMOJkGE1bQ7lQUtF2Uxx3y7uhEROricVxmFsCVeoO3uNx/hJtqa5SlyKH/xgu7G3ua/lNWWdWovHPcVRwaS46AXzskCK6xxnxHaRX9lTLDuxsSgRt1MRSAE8Per9BCKOlCGI2dIv0xOHDAR1XkS4UyDEwU7BCdFKPUB8zh1CNu7qIAVutBFlwN1Ic7RXjBM7JVC9ZsZmg0QDtwXQw5ljdSkwH1oYprU2XZwqIOolIih5pXPWUaaodL/J4kl+1Wzy7TYpgaN5agWyg1Y9d/jpbnKdBYS0LfQk+7BTq7YkoQWvx3/PJ+ZU/kGcced8vgJQ/vj6xMtJj5Ji9R2kzYp9ct8u5/WHTGSsl6vN2lu6P4bdeJqsBWlJ0ZFv4FXzyUP0EWzN80RLiCtrqEjj/IKz3w== tm@connectedcars.dk\" >> ~/.ssh/authorized_keys"
auth-wrapper ssh -v support@192.168.7.1 "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys"
