#!/bin/bash
. plusScriptsPaths

$PS_DIR/+/+extract accel-logs.tar.gz
$PS_DIR/+/+extract accel-calibration-logs.tar.gz    
cd data
drb-decoder -t accel-calibration decode -i ./raw-accel-calibration-logs 
drb-decoder -t accel decode -i ./raw-accel-logs