#!/bin/bash
. plusScriptsPaths

$PS_DIR/+/+extract accel-logs.tar.gz
$PS_DIR/+/+extract accel-calibration-logs.tar.gz    

filename="gyro-logs.tar.gz"

if [ -e "$filename" ]; then
  echo "File $filename exists."

  # Check if the archive is empty
  if [ $(tar -tzf "$filename" | head -1 | wc -l) -gt 0 ]; then
    echo "The archive is not empty. Extracting..."
    tar -xzf "$filename"
  else
    echo "The archive is empty."
  fi
else
  echo "File $filename does not exist."
fi

cd data
drb-decoder -t accel-calibration decode -i ./raw-accel-calibration-logs 
drb-decoder -t accel decode -i ./raw-accel-logs