#!/bin/bash
TARGET=$1
ARTIFACT_TYPE=$2
SHA=$3

[[ "$TARGET" == port* ]] || { echo "Not a valid port"; exit 255; }

DEVICE_TYPE=$(auth-wrapper ssh $TARGET "hostname")
echo "Target $DEVICE_TYPE"

ARTIFACT="$ARTIFACT_TYPE-$DEVICE_TYPE.ccupd"
echo "Artifact $ARTIFACT"

RELEASE_URL="https://storage.googleapis.com/connectedcars-device-updates/$ARTIFACT_TYPE/$SHA/full/$ARTIFACT"

echo "Release URL $RELEASE_URL"
TMP_DIR="/tmp"
TMP_FILE="$TMP_DIR/$ARTIFACT"

echo "Local path $TMP_DIR"

function download() {
    echo "Local dest: $1"
    if curl --head --fail --silent -o /dev/null "$1";
    then
      echo "The page exists"
    else
      echo "The page does not exist!"
      exit 255
    fi
    echo "curl -C - -s $1 --output $2"
    curl -C - -s $1 --output $2
}

download $RELEASE_URL "$TMP_FILE"

[[ -s $TMP_FILE ]] || { echo "File is empty"; exit 255; }

auth-wrapper scp $TMP_FILE $TARGET:/tmp

auth-wrapper ssh -t $TARGET "source /etc/profile && sudo ccupd -v install /tmp/$ARTIFACT "
