#!/bin/bash

TARGET=$1

# [[ "$TARGET" == port* ]] || { echo "Not a valid port"; exit 255; }

STATE_FILE_NAME=$(auth-wrapper ssh $TARGET "ls /data/state_*")
INTERNAL_STATE_FILE_NAME="/data/internal_state.json.gz"

echo "Target $STATE_FILE_NAME"

auth-wrapper rsync -chavzP $TARGET:$STATE_FILE_NAME .
auth-wrapper rsync -chavzP $TARGET:$INTERNAL_STATE_FILE_NAME .

gzip -d -f $(basename "$STATE_FILE_NAME") 
gzip -d -f $(basename "$INTERNAL_STATE_FILE_NAME") 






