#!/bin/bash

BASELINE_DEPLOY=/home/thm/workspace/223_SAS_IMAGES/BASELINE_DEPLOY

plauFolder(){
  rm $1/*
  touch "$1/djall-version.log"
  echo "Deploy files from $(pwd)" >> "$1/djall-version.log"
}


forFw() {
  FW_DEPLAY_PATH="$BASELINE_DEPLOY/FW"
  plauFolder $FW_DEPLAY_PATH
  cp -a . "$FW_DEPLAY_PATH"
}


forSw() {
  SW_DEPLAY_PATH="$BASELINE_DEPLOY/SW"
  plauFolder $SW_DEPLAY_PATH
  cp -a . "$SW_DEPLAY_PATH"
}

runDeploy(){
  cd $BASELINE_DEPLOY
  $BASELINE_DEPLOY/deploy.sh
}


[ $1 = "-fw" ] && forFw $2
[ $1 = "-sw" ] && forSw $2
[ $2 = "-r" ] && runDeploy $2
