#!/bin/bash

# Define the remote host
remote_host="username@remote_host"

# Run the gcloud command on the remote machine and capture the output
output=$(auth-wrapper ssh -T $remote_host "gcloud auth login --update-adc 2>&1")

# Print the output
echo "$output"

# Extract the URL from the output
extracted_url=$(echo "$output" | grep -oP '(?<=gcloud auth login --remote-bootstrap=").*(?=")')

# Check if the URL extraction was successful
if [ -n "$extracted_url" ]; then
    # Copy the URL to the clipboard
    # For Linux, using xclip:
    echo "$extracted_url" | xclip -selection clipboard

    # For macOS, using pbcopy:
    # echo "$extracted_url" | pbcopy

    echo "URL copied to clipboard."
else
    echo "URL extraction failed."
fi




#  nuc