#!/bin/bash
. plusScriptsPaths

# Check if any of the arguments are "-p"
persist="false"

if [ "$1" == "-p" ]; then
  persist="true"
  shift
fi

if [ "$2" == "-p" ]; then
  persist="true"
fi

device=$1

if [ -z "$device" ]; then
  select_port 
  device="$SELECTED_DEVICE"
fi

if [ "$persist" == "true" ]; then
  while true; do 
    expect "$PS_DIR_WORKERS/device_ssh_init.exp" "$device"  "$PS_DIR_WORKERS/device.rc" 
  done
else 
  expect "$PS_DIR_WORKERS/device_ssh_init.exp" "$device"  "$PS_DIR_WORKERS/device.rc" "export PS1=\"\\\[\\e[33m\\]$device\\\[\\e[32m\\]@\\h:\\[\\e[34m\\]\\w\\[\\e[0m\\]\\# \""


fi

