#!/bin/bash
. plusScriptsPaths

# Check if any of the arguments are "-p"
persist="false"

if [ "$1" == "-p" ]; then
  persist="true"
  shift
fi

if [ "$2" == "-p" ]; then
  persist="true"
fi

device=$1

if [ -z "$device" ]; then
  select_port 
  device="$SELECTED_DEVICE"
fi

if [ "$persist" == "true" ]; then
  while true; do 
    python "$PS_DIR_WORKERS/device_ssh_init.py" "$PS_DIR_WORKERS/device.rc" "$device"
  done
else 
  python "$PS_DIR_WORKERS/device_ssh_init.py" "$PS_DIR_WORKERS/device.rc" "$device"
fi