#!/bin/bash
. plusScriptsPaths

persist_name=$(basename "$0")

file_trans=$2
device=$1

echo "device" $device

if [ -z "$device" ] 
then
  select_port 
  device="$SELECTED_DEVICE"
fi

if [ -z "$file_trans" ]
then
  path_hash=$(echo -n "$(pwd)" | sha256sum | awk '{print $1}' | cut -c 1-8)
  files=$(ls -A1 | grep -v '~$' | tr '\n' ' ' | sed 's/ *$//')
  file_trans=$(plus-menu --items "$files" --persist-path "$persist_name-$path_hash" --prompt-msg "Select file/folder to transfer" ) 
  echo "$file_trans"
fi


echo "auth-wrapper rsync -avz $file_trans $device:/data/support/$3" 
auth-wrapper rsync -avzP "$file_trans" "$device":/data/support/"$3"