#!/bin/bash

# . plusScriptsPaths
# $PS_DIR/+extract

PS_DIR_PLUS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PS_DIR=${PS_DIR_PLUS%/*}
PS_DIR_CONFIG=$PS_DIR/config
PS_DIR_INSTALL=$PS_DIR/install
PS_DIR_WORKERS=$PS_DIR/workers
PS_DIR_RELEASES=$PS_DIR/releases

# GITROOT="$(git rev-parse --show-toplevel)"

print_title() {
    echo -e "\033[1;4;36m$1\033[0m"
}

print_link() {
    echo -e "\033[1;4;34m$1\033[0m"
}


start_time=$(date +%s)

start_spinner() {
    local message=$1
    spinner=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")

    YELLOW='\033[1;33m'
    NC='\033[0m' # No Color

    # Start the spinner in the background
    (
      while :; do
        for i in "${spinner[@]}"; do
          printf "\r${message} ${YELLOW}${i}${NC} "
          sleep 0.1
        done
      done
    ) &
    # Save the PID of the spinner
    spinner_pid=$!
}


stop_spinner() {
    # Kill the spinner
    kill $spinner_pid

    # Clear the line
    printf "\r\033[K"
}


# Declare the mapping of IDs to names
declare -A ids_to_names
ids_to_names=(
    ["port2"]="logi02"
    ["port4"]="logi04"
)
