#!/bin/bash

install() {
  echo "Command not supported: $1"
}

build() {
  BUILD_PLATFORMS=${BUILD_PLATFORMS:='linux/amd64 linux/arm64'}

  # External variables
  PROJECT_ID=${PROJECT_ID:='connectedcars-staging'}
  COMMIT_SHA=${COMMIT_SHA:='local'}
  BRANCH_NAME=${BRANCH_NAME:=$(git symbolic-ref --short -q HEAD)}
  BUILD_IMAGE=${BUILD_IMAGE:='y'}
  BUILD_SDK=${BUILD_SDK:='n'}
  PUSH=${PUSH:='n'}

  DOCKER_OPTIONS=${DOCKER_OPTIONS:-}

  echo "Build image artifacts"
  ./build-image.sh
}

deploy() {
    echo "Deploying to $2"
    build "$@"
  ./ccupd-target.sh rootfs $2
}

test() {
  echo "Command not supported: $1"
}

pre_push() {
  echo "Command not supported: $1"
}

case "$1" in
  install)
    install "$@"
    ;;
  build)
    build "$@"
    ;;
  deploy)
    deploy "$@"
    ;;
  test)
    test "$@"
    ;;
  pre_push)
    pre_push "$@"
    ;;
  *)
    echo "Command not supported: $1"
    exit 1
    ;;
esac
