#!/bin/bash

install() {
  npm install
}

build() {
  npm run build
}

deploy() {
  ./app-ccupd.sh && +scp-to-device $2 app-imx6ul.ccupd && auth-wrapper ssh -t $2 "source /etc/profile && sudo ccupd install /data/support/app-imx6ul.ccupd"
}

test() {
  if [ "$2" == "update-snap" ]; then
    echo "Updating snapshot..."
    npm run test -- -u
  else 
    npm run test
  fi
}

pre_push() {
  npm run pre-push
}

clean() {
  echo "Remove the build folder"
  rm -rf build
  echo "Remove the node_modules folder"
  rm -rf node_modules
  if [ -f "app-imx6ul.ccupd" ]; then
    echo "Remove the app-imx6ul.ccupd file"
    rm app-imx6ul.ccupd
  fi
  dye yellow bold "Please run \"+build install\" and \"+build build\" commands"
}


case "$1" in
  install)
    install "$@"
    ;;
  build)
    build "$@"
    ;;
  clean)
    clean "$@"
    ;;
  deploy)
    deploy "$@"
    ;;
  test)
    test "$@"
    ;;
  pre_push)
    pre_push "$@"
    ;;
  *)
    echo "Command not supported: $1"
    exit 1
    ;;
esac
