#!/bin/bash

install() {
  npm install
}

build() {
  npm run build:js && npm run gen-types && npm run build
}

deploy() {
  BUILD_DIR="$(pwd)"/build/dist/ OUTPUT_DIR=generated-config node "$(pwd)"/build/dist/bin/generate-config.js src/configs/vag/vw/vw-id4-id5-e2-2003-electric-2024-2025.ts
}

test() {
  if [ "$2" == "update-snap" ]; then
    npm run test -- -u
  else 
    npm run test
  fi
}

pre_push() {
  test "$@"
}

case "$1" in
  install)
    install "$@"
    ;;
  build)
    build "$@"
    ;;
  deploy)
    deploy "$@"
    ;;
  test)
    test "$@"
    ;;
  pre_push)
    pre_push "$@"
    ;;
  *)
    echo "Command not supported: $1"
    exit 1
    ;;
esac
