

I neet an expect script that does this: 

❯ +ssh 100.65.253.43 #V3-2
100.65.253.43
Last login: Fri Jun 16 11:09:07 2023 from 10.8.0.183
support@iwg26-v3-ag:/data/support$ sudo su
root@iwg26-v3-ag:/data/support# cd ..
root@iwg26-v3-ag:/data# rm -rf *logs
root@iwg26-v3-ag:/data# # ctrl + d
support@iwg26-v3-ag:/data/support$ # ctrl + d 
Connection to 100.65.253.43 closed.


I need it to take the ip as an argument. And it needs to be able to run multiple devices. heres is the promt on a different device: 

❯ +ssh 100.64.197.31 #V2-2
100.64.197.31
Last login: Fri Jun 16 11:09:28 2023 from 10.8.0.183
support@iwg26-v2:/data/support$

The connection is a extremly slow 2g connection. 